### ISSUE TITLE
Meaning of flymake message

### ISSUE THREAD

**Issue by Esnos33** [SWI-Prolog/packages-sweep#3]
Hi, I will be learning Prolog this semester and want to do Prolog using this major-mode. Everything works just fine, but the only problem I have is that I don't know what a flymake warning means, and I can't find its definition.

For example, when I have this code in buffer
```
max(X, Y, X) :- X >= Y, !.
max(X, Y, Y).
```
I get following notes:
```
Line  Col Type Backend Message
1     0   note s-d-f   Unreferenced definition for max/3
2     0   note s-d-f   Unreferenced definition for max/3
2     4   note s-d-f   Singleton variable
```
and I don't know what flymake wants me to change. I tried to search in your manual, I searched internet for messages, I searched what `s-d-f` is and I searched your code only to find https://github.com/SWI-Prolog/packages-sweep/blob/bd31199a34c0619b346954f25875fcb7239e2b86/sweeprolog.el#L3207 which doesn't tell me anything.

Do you know where I can find definitions of flymake errors?

**Comment by eshelyaron** [comment]
Hi @Esnos33,

These message are defined in `sweeprolog-analyze-fragment-flymake`.

`s-d-f` is a shorthand that Flymake produces.  If you hover over it with your mouse or put your cursor on it and hit `C-h .`, it tells you what it stands for: `From ‘sweeprolog-diagnostic-function’ backend`

"Unreferenced definition for max/3" means that you've defined a predicate (`max/3`) that isn't used anywhere, there are no references to this predicate.  Once you use this predicate in some other definition, or _export_ it for use from other files, this diagnostic will go away.  For example you can add the line `:- public max/3.` to tell Prolog that this predicate is used from elsewhere.
"Singleton variable" says this variable is a singleton, it only occurs once.  Singleton variables are meaningless, and often correspond to programmer errors (typos).   If you don't use a variable, you should name it `_` or `_X`.  This indicates that you're intentionally ignoring this variable.  See also https://www.swi-prolog.org/pldoc/man?section=singleton

I feel that these messages are quite clear, but let me know if you have improvement suggestions.  Perhaps we can make them more beginner friendly, as long as they do not become too verbose.

Good luck!

**Comment by Esnos33** [comment]
Hi @eshelyaron 

This was a very good explanation of what these flymake notes do; I now understand them clearly. I wouldn't change flymake messages, but maybe I would add these two examples to the info because these are things that probably every new Prolog user would encounter. 

I would also add to info chapter [Interacting with the Top-level](top-level https://eshelyaron.com/sweep.html#Interacting-with-the-Top_002dlevel) information that you can press `h` for an explanation of all possible actions and that `y` also works as stop and `space` works as stop instead of redo
```
likes(ellen,tennis).
likes(john,football).
likes(tom,baseball). /* facts */
likes(eric,swimming).
likes(mark,tennis).
likes(bill,X) :- likes(tom,X). /* rule */
```
```
?- likes(Y, baseball).
Y = tom h
  Possible actions:
  ; (n,r,space,TAB): redo              | t:         trace&redo
  *:                 show choicepoint  | c (a,RET): stop
  w:                 write             | p:         print
  b:                 break             | h (?):     help

Action?  

?- likes(Y, baseball).
Y = tom ;
Y = bill.

?- likes(Y, baseball).
Y = tom y

?- likes(Y, baseball).
Y = tom  

?- likes(Y, baseball).
Y = tom c

?- 
```

**Comment by eshelyaron** [comment]
Thanks, I'll look into expanding the documentation a bit.
For now, I've [extended](https://github.com/SWI-Prolog/packages-sweep/commit/f6df971ed6513c091a62eca045ebe981d46fa169) the "Singleton variable" message to say "Singleton variable, use C-c C-_ to replace with anonymous variable."
The `C-c C-_` mentioned here is a new command which replaces the variable (or other term) at point with an anonymous variable.
This will be included in the next Sweep release.

**Comment by JanWielemaker** [comment]
PceEmacs has C-c C-s that checks the syntax.   If invalid, it moves the caret to the
location of the syntax error.   It valid, but there are singletons, it iterates through the
singletons, where `y` replaces the current `Var` with `_Var`.

**Comment by eshelyaron** [comment]
Hi @JanWielemaker :)
Thanks, that works nicely.  We could add something similar to Sweep, although I think it would be ideal to iterate over all diagnostics, not just singleton variables, and suggest fixing them one by one.  If we could associate some fix procedure with each diagnostic, that'd be easy to achieve.  Unfortunately, Emacs's Flymake has no notion of fixes.
I've extended Flymake with such a facility in my own fork, and suggested it for upstream, but I'm afraid the discussion around that reached somewhat of a dead end.  See https://yhetil.org/emacs/m1ikye5z6l.fsf@dazzs-mbp.kpn/
We could go with some bespoke UI for suggesting fixes instead of relying on Flymake, that'd require some work but may lead to a nicer UX overall.  I'll give it some thought!

**Comment by JanWielemaker** [comment]
Easy fixing would be really nice.  Unfortunately the parser does not give a great deal of information on how to fix things.   Considering the lack of keywords and the existence of operators, this is probably hard.  Nice challenge though.    Most likely LLMs can fix most broken syntax :smile:
