### ISSUE TITLE
Saving files takes longer and longer the longer I use Sweep in a buffer

### ISSUE THREAD

**Issue by camsaul** [SWI-Prolog/packages-sweep#4]
I installed Sweep earlier this week to play around with it and generally it works ok but slow file save times are really making my life hard.

The longer I have Sweep running in a buffer, the longer it takes to save a file. It's a little slow to start off with (taking several seconds to save a file) but after working on a file for an hour or so it takes several minutes to save... I've waited over 10 minutes to save a ~100 LoC file without success. Usually at some point I just have to resort to stopping the save with `C-g` and copying the entire file into a new buffer and saving it there. Opening a new Sweep buffer to save to a new file makes things fast again, so things are definitely getting progressively slower on a per-buffer basis rather than a global one. 

![save](https://github.com/user-attachments/assets/45e06734-8518-4118-a134-b25bba35202c)

I have garbage collection messages enabled, and it's just thrashing, constantly garbage collecting in a desperate attempt to save the file. I raised my GC cons threshold  to 1 GB and it still thrashes... my file is only ~100 LoC.

Not sure what's going on but the font locking gets progressively more broken the longer I work on a file as well, I'm wondering if maybe it's accumulating more font-locking rules as time goes on and it's grinding to a halt trying to satisfy all of them.

I can load files with `C-c C-l` instantly so I don't think there's any problem with communicating with `swipl`, and saving files in other major modes works fine... just Sweep has an issue.

**Comment by eshelyaron** [comment]
Hi there @camsaul, thanks for reporting this issue.
Could you tell us more about your setup or provide a (preferably) minimal reproducible example?
Sweep doesn't interfere with buffer saving in any direct way, so this is most probably caused by some interaction with something else in your setup that runs while saving a buffer.
Also, you can use `toggle-debug-on-quit` and then hit `C-g` while trying to save: that should give us a backtrace that'll hopefully shed more light on what exactly stalls.

**Comment by camsaul** [comment]
Hey @eshelyaron, thanks for the suggestion. I enabled debug and quit and the stacktrace showed me it looks like some sort of weird interaction between [`rainbow-delimiters-mode`](https://github.com/Fanael/rainbow-delimiters) and [`undo-tree-mode`](https://github.com/emacsmirror/undo-tree/blob/master/undo-tree.el)... disabling them both solved my issues. My undo tree files are actually around 2 GB for the 100 LoC Prolog file in question! It's filled with stuff related to rainbow delimiters mode refontifying the current buffer... not sure why that's even in the undo log in the first place since I didn't issue that command interactively. Anyways, I'll look into why they're acting crazy here. I use both modes with other languages without issue FWIW.
